language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: ZhlzghomxvBOT3p7/LmziMo25n/LIjLYuHWWuDXkuwLnYZ+eTdr8kzDKAB1j6YgOe+ccPqs3q6AF/HXIFISO0FkYqoQ4G7bv/UCNAbnI2dmBIIH893AqgPLz58+tXneihbNuagpUfAHnvCoR9CcKqOSbtgdqLhiVcq+dxq0JoSk=
  app: intense-crag-5568
  on:
    repo: matsumo1001/rakuten_enpit_example
